root: true
extends:
  - '@react-native-community'
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    typescript: {}
rules:
  import/order:
    - error
    - pathGroups:
        - pattern: "@src/**"
          group: parent
      groups:
        - builtin
        - external
        - parent
        - sibling
        - index
      newlines-between: always
